# Generated by Django 3.2.4 on 2022-05-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='blurhash',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
