# Generated by Django 3.2.4 on 2022-05-24 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0003_auto_20220523_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
