# Generated by Django 3.2.4 on 2022-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0004_auto_20220524_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
