# Generated by Django 3.2.4 on 2022-06-02 16:01

from django.db import migrations, models
import floatapp.models
import floatapp.storages


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0005_auto_20220525_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, storage=floatapp.storages.PrivateMediaStorage(), upload_to=floatapp.models.file_upload_path),
        ),
    ]
