# Generated by Django 3.2.4 on 2022-06-14 14:00

from django.db import migrations, models
import floatapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0006_auto_20220602_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to=floatapp.models.file_upload_path),
        ),
    ]
