# Generated by Django 3.2.4 on 2022-06-14 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0008_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
