# Generated by Django 3.2.4 on 2022-06-23 04:26

from django.db import migrations, models
import floatapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0009_alter_screenshot_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_width',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, height_field='screenshot_height', upload_to=floatapp.models.file_upload_path, width_field='screenshot_width'),
        ),
    ]
