# Generated by Django 3.2.4 on 2022-06-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0012_alter_screenshot_screenshot_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='metadata',
        ),
    ]
