# Generated by Django 3.2.4 on 2022-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0014_remove_screenshot_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='metadata',
            field=models.JSONField(default=list),
        ),
    ]
