# Generated by Django 3.2.4 on 2022-06-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0015_screenshot_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='screenshot_width',
        ),
    ]
