# Generated by Django 3.2.4 on 2022-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0016_remove_screenshot_screenshot_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='screenshot_width',
            field=models.IntegerField(default=1920),
        ),
    ]
