# Generated by Django 3.2.4 on 2022-06-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0017_screenshot_screenshot_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='blurhash',
        ),
    ]
