# Generated by Django 3.2.4 on 2022-06-25 16:10

from django.db import migrations, models
import floatapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('floatapp', '0018_remove_screenshot_blurhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='blurhash',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, height_field='screenshot_height', upload_to=floatapp.models.file_upload_path, width_field='screenshot_width'),
        ),
    ]
